version: '3.2'
services:
    tess-front:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app/src
        environment:
            - REACT_APP_NAME=test
        env_file:
            - ./.env
